[features]
seeds = false
[programs.devnet]
nft_marketplace = "4PYm9iCSmNQokAATfDdAsHzQsiXkcCSNTUzQU8MisNTK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/mnt/c/users/joeca/onedrive/desktop/me/coding-and-crypto/nft-marketplace/wallet/keypair.json"

[scripts]
test-mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint.ts"
test-bid = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-bid.ts"
test-sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-sell.ts"
